### ISSUE TITLE
License not declared 

### ISSUE THREAD

**Issue by Shumigaj** [formulahendry/vscode-auto-rename-tag#553]
I can't find a license associated with this extension and therefore can't legally install it.
Could you please add a license to this project and release new version with chosen license?

**Comment by spoenemann** [comment]
The repository has the [MIT license](https://github.com/formulahendry/vscode-auto-rename-tag/blob/master/LICENSE), so I assume that is also valid for the VS Code extension.

@formulahendry could you copy the license file into each package, especially the extension? This is required by the license itself:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

It would also be great to add `"license": "MIT"` to each package.json file.

See also #71.

**Comment by Shumigaj** [comment]
Thanks. I missed changes in the repository after I created this request

**Comment by spoenemann** [comment]
Unfortunately, since the license is not packaged with the extension and the package.json does not declare a license identifier, the extension cannot be published to https://open-vsx.org/

**Comment by adremides** [comment]
@spoenemann [Auto Close Tag](https://github.com/formulahendry/vscode-auto-close-tag) didn't declare a license identifier in the package.json but it is already in open-vsx. And what do you mean by license is not packaged with the extension? what it takes to have it? can us fork it and make a PR with the required changes?
From the time the issue was made I guess the owner didn't saw it. Maybe with some action for him/her to see it (like making a pull request) solves this and we all benefit from this amazing tool.

**Comment by spoenemann** [comment]
Copying LICENSE into `packages/extension/` and adding `"license": "MIT"` to package.json should solve the issue. Yes, creating a PR might help.
